name: Release

on:
  push:
    branches:
    - 'master'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate versions
      uses: HardNorth/github-version-generate@v1.1.2
      with:
        version-source: file
        version-file: gradle.properties
        version-file-extraction-pattern: '(?<=version=).+'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Release with Gradle
      id: release
      run: |
        ./gradlew build -Prelease.useAutomaticVersion=true \
        -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} \
        -Prelease.newVersion=${{ env.NEXT_VERSION }}
        
    - name: Release Changelog Builder
      uses: mikepenz/release-changelog-builder-action@v3.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: ${{steps.github_release.outputs.changelog}}
        files: build/libs/tenor-${{ env.RELEASE_VERSION }}.jar
        
